name: Remote SSH Command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host:  20.193.149.223
          username: azureuser
          KEY: ${{ secrets.PRIVATE_KEY }}
          port:  22
          script:  ls && cd birthday && git pull && npm install && npm run build &&  npm start
